In [2]:
import qimax.gate
import numpy as np
%load_ext autoreload
%autoreload 2

In [10]:
for i in range(0, 10):
    k = np.kron(gate.gate['I'],gate.gate['H'])


In [ ]:
for i in range(0, 1000000):
    k = gate.gate['IH']

In [10]:
A = np.random.uniform(0,2*np.pi,(2**15, 2**15))

In [12]:
A @ np.ones(2**15)

array([102899.83947437, 102570.91444041, 102992.24811631, ...,
       103653.72500952, 103321.13151543, 102951.52620608])

In [4]:
for i in range(1):
    k = np.kron(A, np.array([[0,0],[0,1]]))

: 

In [7]:
A @ A

In [65]:
import tensor
k1 = tensor.ARY(A, 1)
print(k1.shape)

(2097152, 80)


In [52]:
import numpy as np

def AP3(A):
    rows, cols = A.shape
    kron_result = np.zeros((2 * rows, 2 * cols))
    kron_result[1::2, 1::2] = A
    return kron_result

# Example usage
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = AP3(A)
print(result)


[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 2. 0. 3.]
 [0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 5. 0. 6.]
 [0. 0. 0. 0. 0. 0.]
 [0. 7. 0. 8. 0. 9.]]
