In [2]:
from qimax import gate
import numpy as np
%load_ext autoreload
%autoreload 2

In [6]:
import random
from qimax import gate
k = 4
gate_list = ['I', 'H', 'S', 'CX', 'RX', 'RY', 'RZ']
gates = random.choices(gate_list, k=k)
tensor_input_forms = []
tensor_string_forms = []
index = 0
if gates[0] in ['RX', 'RY', 'RZ']:
    phase = random.uniform(0, 2*np.pi)
    tensor = gate.gate[gates[0]](phase)
    tensor_input_forms.append(f"{gates[0]} {phase} {index}")
    index += 1
else:
    tensor = gate.gate[gates[0]]
    if gates[0] == 'CX':
        tensor_input_forms.append(f"{gates[0]} {index} {index+1}")
        index += 2
    else:
        tensor_input_forms.append(f"{gates[0]} {index}")
        index += 1
for gate1 in gates:
    if gate1 in ['RX', 'RY', 'RZ']:
        phase = random.uniform(0, 2*np.pi)
        tensor = np.kron(tensor, gate.gate[gate1](
            phase))
        tensor_input_forms.append(f"{gate1} {phase} {index}")
        index += 1
    else:
        tensor = np.kron(tensor, gate.gate[gate1])
        if gate1 == 'CX':
            tensor_input_forms.append(f"{gate1} {index} {index+1}")
            index += 2
        else:
            tensor_input_forms.append(f"{gate1} {index}")
            index += 1
for i in range(tensor.shape[0]):
    for j in range(tensor.shape[1]):
        tensor_string_forms.append(f"{i} | {j} | {tensor[i,j]}")
np.savetxt(f'./data_hardware/tensor/in_{k}.txt', tensor_input_forms, fmt='%s')
np.savetxt(
    f'./data_hardware/tensor/out_{k}.txt', tensor_string_forms, fmt='%s')

In [47]:
from qiskit import QuantumCircuit, transpile
from qiskit.circuit.library import RZGate

# Create a quantum circuit
qc = QuantumCircuit(2)
qc.swap(0,1)

# Transpile the circuit
transpiled_circuit = transpile(qc, basis_gates=['h','s','cx','rx','ry','rz'])

# Print the transpiled circuit
print(transpiled_circuit)

          ┌───┐     
q_0: ──■──┤ X ├──■──
     ┌─┴─┐└─┬─┘┌─┴─┐
q_1: ┤ X ├──■──┤ X ├
     └───┘     └───┘


In [ ]:
for i in range(0, 1000000):
    k = gate.gate['IH']

In [10]:
A = np.random.uniform(0, 2*np.pi, (2**15, 2**15))

In [12]:
A @ np.ones(2**15)

array([102899.83947437, 102570.91444041, 102992.24811631, ...,
       103653.72500952, 103321.13151543, 102951.52620608])

In [4]:
for i in range(1):
    k = np.kron(A, np.array([[0, 0], [0, 1]]))

: 

In [7]:
A @ A

In [65]:
import tensor
k1 = tensor.ARY(A, 1)
print(k1.shape)

(2097152, 80)


In [52]:
import numpy as np


def AP3(A):
    rows, cols = A.shape
    kron_result = np.zeros((2 * rows, 2 * cols))
    kron_result[1::2, 1::2] = A
    return kron_result


# Example usage
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = AP3(A)
print(result)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 2. 0. 3.]
 [0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 5. 0. 6.]
 [0. 0. 0. 0. 0. 0.]
 [0. 7. 0. 8. 0. 9.]]
